import type { Metadata } from 'next';
import React from 'react';

import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
	title: 'Home - Shoolin Construction',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
